version: 2.1
orbs:
  gem: zfhui/ruby-gem@0.1.0
jobs:
  test-with-ruby-2-6-5:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.6.5
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 2.0.1
  test-with-ruby-2-3-6:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.3.6
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 1.16.1
  deploy:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.6.5
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            gem build blinkist-airbrake-scrubber.gemspec
            gem push "blinkist-airbrake-scrubber-$(git describe --tags | cut -c2-).gem"

workflows:
  test:
    jobs:
      - test-with-ruby-2-6-5
      - test-with-ruby-2-3-6
      - deploy:
          requires:
            - test-with-ruby-2-6-5
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
